### PR TITLE
Customer Name Change and Tax Rate Change

### LINKED ISSUE #1: Default Tax Rate Issue
The default tax rate 10% leads to wrong calculation with core systems, ref:IM7542

### LINKED ISSUE #3: Last Name Issue
Last name should be second name + family name

### PR DESCRIPTION
**Pull request by ihab82**
Last Name change and default tax rate change

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ var customerProfile = /** @class */ (function () {
     return customerProfile;
 }());
 var cusProfile = new customerProfile();
-console.log("Customer Name: " + cusProfile.getCustomerName("Ihab", "Kassem"));
+console.log("Customer Name: " + cusProfile.getCustomerName("Ihab", "Mohamad Kassem"));
```
Comment (ihab82) [inline test.js:33]: Unit testing is required by minimum two scripts

**Review by ihab82 — COMMENTED** [review]
Done

File: test.js (hunk 1 above)
Comment (ihab82) [reply test.js:33]: Done
